<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>0.6.1</Version>
    <ApplicationIcon>img\logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="img\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NModbus" Version="3.0.83" />
    <PackageReference Include="NModbus.Serial" Version="3.0.83" />
  </ItemGroup>



</Project>
